/*
 * Tyler Kelley
 * CS2263 Griffith
 * Homework 1 9/17/2021
 */
/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package edu.isu.cs2263.hw01;
//import org.apache.commons.cli.Options;
public class App {

    public static void main(String[] args) {
        System.out.print("Issues with apache cli");
    /*
        //create a new options object to add our options too
        Options options = new Options();
        //create the new options that are available
        options.addOption("b", "batch <file>", false, "batch file that contains the expressions you want to evaluate");
        options.addOption("o", "output <file>", false, "output file we put our evaluations in");
        options.addOption("h", "help", false, "print usage message for available options");
        //create a new command line parser so we can output results
        CommandLineParser parser = new DefaultParser();
        CommandLine cmdInput = parser.parse(options, args);

        if (cmdInput.hasOption("b")){
            System.out.println("Batch Value: ");
        }
        if(cmdInput.hasOption("o")){
            System.out.println("Output Value :");
        }

     */
        //help format to output the -h output
        //HelpFormatter formatter = new HelpFormatter();
        //formatter.printHelp("eval", newOptions());

    }
}
